### PR TITLE
Fix: Error when no next filter is provided with response modes

### LINKED ISSUE #36: Fix `darwin` and `both` mode when no next filter is provided
When `next_filter` is empty, the manager generates a path like : `/path/to/.sock`.

When such a path is set in a filter and the response mode is set to `darwin` or `both`, the filter tries to connect to it and fails _(File not found)_.

### PR DESCRIPTION
**Pull request by HugoSoszynski**
Resolve #36 

When no next_filter is provided, set the filter parameter to `no`.

When the next filter socket path is equal to `no` in a filter, no longer tries to connect to it.
Outputs a Notice level log.

Corrected a log line.

### CODE REVIEW

File: samples/base/Session.cpp [hunk 1]
```diff
@@ -57,6 +57,12 @@ namespace darwin {
 
     void Session::SendToDarwin() noexcept {
         DARWIN_LOGGER;
+
+        if (!_next_filter_path.compare("no")) {
```
Comment (frikilax) [inline samples/base/Session.cpp]: au final, laisser une string vide n'aurais pas permis un traitement plus rapide ?
